In [63]:
import csv
import codecs
import sys
import io
import numpy as np
import pandas as pd
import scipy as sp

In [64]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from statistics import mean

In [133]:
from sklearn import svm
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn import tree
from sklearn import linear_model
from sklearn.linear_model import ElasticNet
from sklearn.kernel_ridge import KernelRidge

In [67]:
from sklearn.metrics import *
from numpy import mean
from numpy import std
from sklearn import metrics

In [88]:
df=pd.read_csv("data_294.csv")

In [90]:
df

Unnamed: 0   1  15  18    21       25       26        39       41  \
0             1  21  23   2  4565  19.2765   8.9368   64.0391  31.8953   
1             2  23  23   2  5633  21.2244  10.3336   74.0391  36.5154   
2             3  25  23   2  6789  23.1790  10.6986  101.5489  38.1809   
3             4  19  23   2  4133  19.1405   8.8411   48.5293  28.3529   
4             5  19  23   2  4133  19.8407   9.3362   48.5293  28.3529   
..          ...  ..  ..  ..   ...      ...      ...       ...      ...   
289         290  24  20   2  7140  24.4034  11.5737   71.8135  35.8413   
290         291  26  20   2  8452  26.3662  11.9433  101.0586  43.6179   
291         292  23  20   2  6531  23.4237  10.3809   81.7744  37.2985   
292         293  25  20   2  7801  25.3843  11.7554   77.0195  44.4808   
293         294  20  20   2  5430  23.0126  10.5810   53.5489  32.7359   

         58        69      83      85        141      155  166    Act  
0    0.0154  200.4442  4.7239  0.5791  1092.3000  60.2772  0.0   1.58  
1    0.0130  287.6204  5.5482  0.5512  1944.0000   0.0000  0.0   1.93  
2    0.0134  257.3209  4.7255  0.5267  1775.2000  71.6216  0.0   2.65  
3    0.0229  173.7359  4.9959  0.5006   704.6495  38.8341  0.0   1.46  
4    0.0229  168.7834  4.1531  0.5455   831.6771  38.5247  0.0   2.95  
..      ...       ...     ...     ...        ...      ...  ...    ...  
289  0.0154  237.5433  5.8331  0.4988  1830.5000  66.9631  0.0   8.00  
290  0.0134  312.0292  6.4319  0.4594  3013.9000  87.6958  0.0   6.70  
291  0.0144  275.1655  6.3289  0.4893  2273.4000  79.4996  0.0  12.90  
292  0.0131  330.3284  7.0198  0.4693  3041.6000  92.1018  0.0   7.50  
293  0.0189  208.2390  5.2572  0.4739  1525.5000  51.7503  0.0   5.60  

[294 rows x 17 columns]

In [91]:
 X = df[['1', '15', '18', '21', '25', '26', '39', '41', '58', '69', '83', '85', '141', '155', '166']]

In [92]:
X

1  15  18    21       25       26        39       41      58        69  \
0    21  23   2  4565  19.2765   8.9368   64.0391  31.8953  0.0154  200.4442   
1    23  23   2  5633  21.2244  10.3336   74.0391  36.5154  0.0130  287.6204   
2    25  23   2  6789  23.1790  10.6986  101.5489  38.1809  0.0134  257.3209   
3    19  23   2  4133  19.1405   8.8411   48.5293  28.3529  0.0229  173.7359   
4    19  23   2  4133  19.8407   9.3362   48.5293  28.3529  0.0229  168.7834   
..   ..  ..  ..   ...      ...      ...       ...      ...     ...       ...   
289  24  20   2  7140  24.4034  11.5737   71.8135  35.8413  0.0154  237.5433   
290  26  20   2  8452  26.3662  11.9433  101.0586  43.6179  0.0134  312.0292   
291  23  20   2  6531  23.4237  10.3809   81.7744  37.2985  0.0144  275.1655   
292  25  20   2  7801  25.3843  11.7554   77.0195  44.4808  0.0131  330.3284   
293  20  20   2  5430  23.0126  10.5810   53.5489  32.7359  0.0189  208.2390   

         83      85        141      155  166  
0    4.7239  0.5791  1092.3000  60.2772  0.0  
1    5.5482  0.5512  1944.0000   0.0000  0.0  
2    4.7255  0.5267  1775.2000  71.6216  0.0  
3    4.9959  0.5006   704.6495  38.8341  0.0  
4    4.1531  0.5455   831.6771  38.5247  0.0  
..      ...     ...        ...      ...  ...  
289  5.8331  0.4988  1830.5000  66.9631  0.0  
290  6.4319  0.4594  3013.9000  87.6958  0.0  
291  6.3289  0.4893  2273.4000  79.4996  0.0  
292  7.0198  0.4693  3041.6000  92.1018  0.0  
293  5.2572  0.4739  1525.5000  51.7503  0.0  

[294 rows x 15 columns]

In [94]:
  y = df['Act']

In [95]:
y

0       1.58
1       1.93
2       2.65
3       1.46
4       2.95
       ...  
289     8.00
290     6.70
291    12.90
292     7.50
293     5.60
Name: Act, Length: 294, dtype: float64

In [96]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.33, shuffle=True)

In [97]:
X_train.shape

(196, 15)

In [99]:
x_test.shape

(59, 15)

In [134]:
regressor = svm.SVR()
regressor = LinearRegression()
regressor = SGDRegressor(max_iter=5000, tol=1e-3)
regressor = KNeighborsRegressor(n_neighbors=5)
regressor = MLPRegressor(hidden_layer_sizes=500, random_state=1, max_iter=100)
regressor = AdaBoostRegressor(random_state=0, n_estimators=100)
regressor = GradientBoostingRegressor(random_state=0)
regressor = tree.DecisionTreeRegressor()
regressor = linear_model.Ridge(alpha=.5)
regressor = linear_model.Lasso(alpha=0.1)
regressor = ElasticNet(random_state=0)
regressor = KernelRidge(alpha=1.0)

In [135]:
 regressor.fit(X_train, y_train)

KernelRidge(alpha=1.0)

In [117]:
y_pred = nn.predict(X_test)

In [107]:
y_pred

array([ 66.69278988,  52.77563688, 329.97990574,  75.86076666,
       197.09131243, 351.59267863, 280.25124926,  34.65830399,
       308.87693445,  65.24148231,  58.42627886,  51.08917235,
       190.25433652,  87.44932157, 303.59155107,  36.72744988,
        55.54882678, 165.98740553,  28.84942736,  46.96059914,
       158.68180789,  20.52259129,  23.4175953 , 283.58295537,
       191.8180407 ,  44.50828358,  62.50052146, 166.95889161,
        65.7061737 ,  68.08569014,  26.69924226, 310.74621556,
       239.31491313, 364.48692147,  55.38753787, 312.593625  ,
        44.76871321,  34.26463402,  94.56894876,  79.14468683,
        72.16760308, 101.15079969, 132.06225259,  54.96290995,
        93.39775461, 101.28664709,  75.97546286, 124.47780293,
       116.4123944 , 105.63395764,  24.13376065, 115.18630535,
       165.11760744,  60.48074586,  72.09685773, 203.33452762,
       126.42857188, 321.78004435,  32.51131924, 117.30564916,
        26.5986721 , 102.89566913,  59.64014325,  33.63

In [139]:
print("\n")
print("overall Performance: ", )



overall Performance: 


In [138]:
  mae = metrics.mean_absolute_error(y_test, y_pred)
  mse = metrics.mean_squared_error(y_test, y_pred)
  r2 = metrics.r2_score(y_test, y_pred)

In [119]:
print (mae, mse, r2)

37.79764992176708 2461.354394046454 0.0036914498059460454


In [123]:
y_pred_train = nn.predict(X_train)

In [127]:
mae1 = metrics.mean_absolute_error(y_train, y_pred_train)
mse1 = metrics.mean_squared_error(y_train, y_pred_train)
r21 = metrics.r2_score(y_train, y_pred_train)

In [128]:
print (mae1, mse1, r21)

39.14308951894411 2688.5753475131387 0.012985118376035998


In [ ]:
#to save the train and test datasets 
x_training, x_test, y_training, y_test = train_test_split(x,y,test_size=.2, random_state = 7000)

In [16]:
#stating the model with default parameter 
nn = MLPRegressor(learning_rate = "constant", activation = "logistic",
          solver ="sgd", hidden_layer_sizes=16, random_state = 0)
nn.max_iter=10000

In [18]:
nn.fit (x_training, y_training)

MLPRegressor(activation='logistic', hidden_layer_sizes=16, max_iter=10000,
             random_state=0, solver='sgd')

In [19]:
print(nn.score(x_test,y_test))

0.03042289740057491


In [20]:
print(nn.score(x_training,y_training))

0.05456590832800079


In [21]:
 # import models multilayer perceptrons
from sklearn.neural_network import MLPRegressor

In [22]:
from sklearn.ensemble import RandomForestRegressor

In [24]:
RF = RandomForestRegressor (n_estimators = 10, random_state = 0)

In [25]:
RF.fit ( x_training, y_training)

RandomForestRegressor(n_estimators=10, random_state=0)

In [26]:
print(RF.score(x_test,y_test))

0.6940017433114501


In [27]:
print(RF.score(x_training,y_training))

0.901042419637758


In [28]:
from sklearn.model_selection import cross_val_score

In [30]:
print(-cross_val_score(nn,x,y.ravel(),cv=5,))

[0.53731459 0.03348758 0.89490941 0.23889833 0.74233842]


In [32]:
print(-cross_val_score(nn,x,y.ravel(),cv=5,).mean())

0.48938966756606084


In [33]:
print(-cross_val_score(RF,x,y.ravel(),cv=5,))

[0.57685392 0.09794421 0.00346931 0.31032728 1.77960249]


In [35]:
print(-cross_val_score(RF,x,y.ravel(),cv=5,).mean())

0.5536394407313991


In [36]:
from sklearn.model_selection import RandomizedSearchCV

In [37]:
# creatting parameter gride
param_grid_nn= {'learning_rate': ['constant','adaptive','invscaling'], 'activation':['identity', 'logistic', 'tanh', 'relu'], 
    'solver': ['adm', 'sgd', 'lbfgs'], 'hidden_layer_sizes': [3,10,30]}

In [50]:
#Instantiate randomized search CV and fit to dataset
nn_random = RandomizedSearchCV(estimator =nn, param_distributions=param_grid_nn, n_iter = 100,
                              cv = 5, verbose =2,
                              n_jobs= -1, scoring = "r2" )
nn_random.fit (x,y)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


C:\Python39\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [-5.63088104e-01             nan             nan -3.90354204e-01
 -4.10793890e-01 -3.40895311e-01 -8.74292012e-01             nan
             nan             nan             nan -1.67055997e+19
 -7.91494494e-02 -6.19675317e+16             nan             nan
             nan             nan -4.25090445e-01             nan
 -6.07879664e-01             nan -6.30953460e-02             nan
             nan -6.78223605e-02             nan -4.43311296e-01
 -6.07879664e-01             nan -4.10793890e-01             nan
             nan -6.78223605e-02 -1.19100331e+17 -1.31274821e+19
 -2.19204017e-01 -4.43311296e-01             nan -3.40895311e-01
 -4.25090445e-01             nan             nan             nan
 -4.97464679e-01             nan -4.44007411e-01 -8.14623346e-02
 -4.05224132e-01 -5.15629832e-01             nan -4.86571357e-01
 -3.95723780e-01 -2.19204

RandomizedSearchCV(cv=5,
                   estimator=MLPRegressor(activation='logistic',
                                          hidden_layer_sizes=16, max_iter=10000,
                                          random_state=0, solver='sgd'),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'activation': ['identity', 'logistic',
                                                       'tanh', 'relu'],
                                        'hidden_layer_sizes': [3, 10, 30],
                                        'learning_rate': ['constant',
                                                          'adaptive',
                                                          'invscaling'],
                                        'solver': ['adm', 'sgd', 'lbfgs']},
                   scoring='r2', verbose=2)

In [51]:
nn_random.best_params_

{'solver': 'lbfgs',
 'learning_rate': 'adaptive',
 'hidden_layer_sizes': 3,
 'activation': 'identity'}

In [52]:
nn1 = MLPRegressor(learning_rate = "adaptive", activation='identity', hidden_layer_sizes=3, max_iter=10000,
             random_state=0, solver='lbfgs')

In [53]:
nn1.fit (x_training, y_training)

MLPRegressor(activation='identity', hidden_layer_sizes=3,
             learning_rate='adaptive', max_iter=10000, random_state=0,
             solver='lbfgs')

In [54]:
print(nn1.score(x_training,y_training))

0.5399655148204336


In [55]:
print(nn1.score(x_test,y_test))

0.5843890926843704


In [56]:
from sklearn.model_selection import cross_validate

In [62]:
scores = cross_validate(nn1,x, y, cv=5                      
                        scoring= "r2",
                        return_train_score=True)

SyntaxError: invalid syntax (<ipython-input-62-4a93aad545ce>, line 2)