In [2]:
# Import Section
import csv
import codecs
import sys
import io
import numpy as np
import pandas as pd
import scipy as sp

# For Regression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from statistics import mean

from sklearn.ensemble import GradientBoostingRegressor

# Python script for confusion matrix creation. 
from sklearn.metrics import *
from numpy import mean
from numpy import std
from sklearn import metrics

In [3]:
dataset=pd.read_csv("data_294.csv")

In [4]:
dataset.shape

(294, 17)

In [5]:
x = dataset[['1', '15', '18', '21', '25', '26', '39', '41', '58', '69', '83', '85', '141', '155', '166']]

In [6]:
x.shape

(294, 15)

In [7]:
y = dataset['Act']

In [8]:
x_model, x_extest, y_model, y_extest = train_test_split(x,y,test_size=.2, random_state = 7000, shuffle=True)

In [9]:
x_model.shape

(235, 15)

In [10]:
x_train, x_test2, y_train, y_test2 = train_test_split(x_model,y_model,test_size=.3, random_state = 7000, shuffle=True)

In [11]:
x_train.shape

(164, 15)

In [12]:
x_test2.shape

(71, 15)

In [13]:
x_val, x_test, y_val, y_test = train_test_split(x_test2,y_test2,test_size=.5, random_state = 7000, shuffle=True)

In [14]:
x_test.shape

(36, 15)

In [15]:
x_val.shape

(35, 15)

In [16]:
regressor = GradientBoostingRegressor(random_state=0)

In [17]:
 regressor.fit(x_train, y_train)

GradientBoostingRegressor(random_state=0)

In [18]:
# compute the testing accuracy
y_pred = regressor.predict(x_test)

In [19]:
y_pred_train = regressor.predict(x_train)

In [20]:
y_pred_train.shape

(164,)

In [21]:
y_pred_val = regressor.predict(x_val)

In [22]:
y_pred_extest = regressor.predict(x_extest)

In [23]:
y_pred_model = regressor.predict(x_model)

In [24]:
  print("\n")
  print("overall Performance: ", )



overall Performance: 


In [25]:
  # model evaluation for testing set
  mae = metrics.mean_absolute_error(y_test, y_pred)
  mse = metrics.mean_squared_error(y_test, y_pred)
  r2 = metrics.r2_score(y_test, y_pred)

In [26]:
print("The model performance for testing set")
print("--------------------------------------")
print('MAE is {}'.format(mae))
print('MSE is {}'.format(mse))
print('R2 score is {}'.format(r2))

The model performance for testing set
--------------------------------------
MAE is 18.860058009950922
MSE is 704.8584074501591
R2 score is 0.5165425295168367


In [27]:
  # model evaluation for training set
maeTrain = metrics.mean_absolute_error(y_train, y_pred_train)
mseTrain = metrics.mean_squared_error(y_train, y_pred_train)
r2Train = metrics.r2_score(y_train, y_pred_train)

In [28]:
print("The model performance for training set")
print("--------------------------------------")
print('MAE is {}'.format(maeTrain))
print('MSE is {}'.format(mseTrain))
print('R2 score is {}'.format(r2Train))

The model performance for training set
--------------------------------------
MAE is 5.218063660519553
MSE is 53.8869400950265
R2 score is 0.9795142528362594


In [29]:
cvscoretrain = (cross_val_score(regressor,x_train,y_train.ravel(),cv=5).mean())

In [30]:
print("The CV score for training set")
print("--------------------------------------")
print (cross_val_score(regressor,x_train,y_train.ravel(),cv=5))
print('Q2 is {}'.format(cvscoretrain))

The CV score for training set
--------------------------------------
[0.28570492 0.33813316 0.28446278 0.8079634  0.57216112]
Q2 is 0.45768507600531105


In [31]:
## model evaluation for extest set
maeex = metrics.mean_absolute_error(y_extest, y_pred_extest)
mseex = metrics.mean_squared_error(y_extest, y_pred_extest)
r2ex = metrics.r2_score(y_extest, y_pred_extest)

In [32]:
print("The model performance for extest set")
print("--------------------------------------")
print('MAE is {}'.format(maeex))
print('MSE is {}'.format(mseex))
print('R2 score is {}'.format(r2ex))

The model performance for extest set
--------------------------------------
MAE is 22.400722785523058
MSE is 1315.583245012531
R2 score is 0.5392350200402862


In [33]:
## model evaluation for val set
maevl = metrics.mean_absolute_error(y_val, y_pred_val)
msevl = metrics.mean_squared_error(y_val, y_pred_val)
r2vl = metrics.r2_score(y_val, y_pred_val)

In [34]:
print("The model performance for val set")
print("--------------------------------------")
print('MAE is {}'.format(maevl))
print('MSE is {}'.format(msevl))
print('R2 score is {}'.format(r2vl))

The model performance for val set
--------------------------------------
MAE is 21.89895601244592
MSE is 842.461734401527
R2 score is 0.7501977639131456


In [35]:
## model evaluation for model set
maemod = metrics.mean_absolute_error(y_model, y_pred_model)
msemod = metrics.mean_squared_error(y_model, y_pred_model)
r2mod = metrics.r2_score(y_model, y_pred_model)

In [36]:
print("The model performance for model set")
print("--------------------------------------")
print('MAE is {}'.format(maemod))
print('MSE is {}'.format(msemod))
print('R2 score is {}'.format(r2mod))

The model performance for model set
--------------------------------------
MAE is 9.7922893154002
MSE is 271.05753850146175
R2 score is 0.8954468592367026


In [39]:
# cv for modeling set 
cvscoremod = (cross_val_score(regressor,x_model,y_model.ravel(),cv=5).mean())

In [41]:
print("The CV score for model set")
print("--------------------------------------")
print (cross_val_score(regressor,x_model,y_model.ravel(),cv=5))
print('Q2 is {}'.format(cvscoremod))

The CV score for model set
--------------------------------------
[0.70759494 0.45227551 0.5319037  0.49178034 0.75506219]
Q2 is 0.5877233372222209


In [32]:
#Randomize search CV
from sklearn.model_selection import RandomizedSearchCV

In [34]:
# creatting parameter gride
param_grid_regressor= {'loss': ['ls', 'lad', 'huber', 'quantile'],
                       'n_estimators':[50,100, 150, 200, 300, 400], 
    'learning_rate': [0.05, 0.1, 0.15, 0.2, 0.25],   'criterion': ['friedman_mse', 'mse', 'mae'],
                       'min_samples_split': [1,2,3,4], 
                     'min_samples_leaf': [1,2,3,4], 'max_depth' : [1,2,3,4,5] }

In [35]:
print (param_grid_regressor)

{'loss': ['ls', 'lad', 'huber', 'quantile'], 'n_estimators': [50, 100, 150, 200, 300, 400], 'learning_rate': [0.05, 0.1, 0.15, 0.2, 0.25], 'criterion': ['friedman_mse', 'mse', 'mae'], 'min_samples_split': [1, 2, 3, 4], 'min_samples_leaf': [1, 2, 3, 4], 'max_depth': [1, 2, 3, 4, 5]}


In [36]:
regressor_random = RandomizedSearchCV(estimator = regressor, param_distributions=param_grid_regressor, n_iter = 100,
                              cv = 5, verbose =2,
                              n_jobs= -1, scoring = 'neg_mean_squared_error' )

In [37]:

regressor_random.fit (x,y)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


C:\Python39\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [           nan -2434.70246077 -3488.07021994 -2474.90138921
            nan -2027.2020153  -2127.54661716 -2384.06793228
            nan            nan -1980.33333119 -1976.09030544
 -2355.82881775 -2606.00568133 -2043.41517031            nan
 -2005.62146151            nan -2143.17941203 -3439.91796497
 -2325.63863882 -2271.83775576            nan -2356.48932984
 -2419.26700637 -2058.17077126 -2031.66757415 -2025.05982813
 -1899.28039552 -2675.37233405 -3470.89997423 -1803.00943444
            nan -1789.48144157            nan -1973.56136624
 -1647.00830207            nan -2077.42335395 -2225.58129389
 -2399.02677854 -1878.58055441 -1943.50431755            nan
 -2145.21461275 -2027.84629892 -1878.25468115            nan
            nan -2970.15364991 -3439.91834711 -2167.99324475
 -2279.63048435            nan -2120.43314501            nan
 -2641.97454244 

RandomizedSearchCV(cv=5, estimator=GradientBoostingRegressor(random_state=0),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'criterion': ['friedman_mse', 'mse',
                                                      'mae'],
                                        'learning_rate': [0.05, 0.1, 0.15, 0.2,
                                                          0.25],
                                        'loss': ['ls', 'lad', 'huber',
                                                 'quantile'],
                                        'max_depth': [1, 2, 3, 4, 5],
                                        'min_samples_leaf': [1, 2, 3, 4],
                                        'min_samples_split': [1, 2, 3, 4],
                                        'n_estimators': [50, 100, 150, 200, 300,
                                                         400]},
                   scoring='neg_mean_squared_error', verbose=2)

In [38]:
regressor_random.best_params_

{'n_estimators': 200,
 'min_samples_split': 2,
 'min_samples_leaf': 3,
 'max_depth': 5,
 'loss': 'lad',
 'learning_rate': 0.1,
 'criterion': 'friedman_mse'}

In [39]:
regressor_random.best_score_

-1647.0083020683844

In [40]:
# parameter tuning grid searchCV
from sklearn.model_selection import GridSearchCV

In [41]:
param_grid_regressor1= {'loss': ['ls', 'lad'],
                       'n_estimators':[ 150, 200, 300], 
    'learning_rate': [0.05, 0.1, 0.15],   'criterion': ['friedman_mse', 'mse'],
                       'min_samples_split': [1,2,3], 
                     'min_samples_leaf': [2,3,4], 'max_depth' : [4,5,6] }

In [42]:
regressor_grid = GridSearchCV(estimator =regressor, param_grid=param_grid_regressor1,
                              cv = 5, verbose =2,
                              n_jobs= -1,  scoring = "neg_mean_squared_error")


In [43]:
regressor_grid.fit (x,y)

Fitting 5 folds for each of 972 candidates, totalling 4860 fits


C:\Python39\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [           nan            nan            nan -2204.22332148
 -2225.69784472 -2236.14275887 -2204.22332148 -2225.69784472
 -2236.14275887            nan            nan            nan
 -2164.32136496 -2189.30291146 -2214.03820563 -2164.32136496
 -2189.30291146 -2214.03820563            nan            nan
            nan -2211.74945746 -2246.46418787 -2274.92823821
 -2211.74945746 -2246.46418787 -2274.92823821            nan
            nan            nan -2287.67352605 -2313.91138344
 -2321.39770105 -2287.67352605 -2313.91138344 -2321.39770105
            nan            nan            nan -2238.81873854
 -2258.1798176  -2273.01111675 -2238.81873854 -2258.1798176
 -2273.01111675            nan            nan            nan
 -2173.99484018 -2180.82407864 -2227.49379313 -2173.99484018
 -2180.82407864 -2227.49379313            nan            nan
            nan -

GridSearchCV(cv=5, estimator=GradientBoostingRegressor(random_state=0),
             n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'mse'],
                         'learning_rate': [0.05, 0.1, 0.15],
                         'loss': ['ls', 'lad'], 'max_depth': [4, 5, 6],
                         'min_samples_leaf': [2, 3, 4],
                         'min_samples_split': [1, 2, 3],
                         'n_estimators': [150, 200, 300]},
             scoring='neg_mean_squared_error', verbose=2)

In [44]:
regressor_grid.best_params_

{'criterion': 'mse',
 'learning_rate': 0.1,
 'loss': 'lad',
 'max_depth': 5,
 'min_samples_leaf': 3,
 'min_samples_split': 2,
 'n_estimators': 150}

In [61]:
regressor_grid.best_score_

-1631.0710092729037

In [68]:
 # manual search engine
regressor1 = GradientBoostingRegressor(criterion = "mse", learning_rate = 0.1, loss = "lad",
                          max_depth = 5, min_samples_leaf = 3, min_samples_split = 2,
                            n_estimators = 150, random_state=0 )

In [69]:
regressor1.fit(x_train, y_train)

GradientBoostingRegressor(criterion='mse', loss='lad', max_depth=5,
                          min_samples_leaf=3, n_estimators=150, random_state=0)

In [70]:
y_pred1 = regressor1.predict(x_test)

In [71]:
y_pred_train1 = regressor1.predict(x_train)

In [72]:
y_pred_val1 = regressor1.predict(x_val)

In [73]:
y_pred_extest1 = regressor1.predict(x_extest)

In [74]:
y_pred_model1 = regressor1.predict(x_model)

In [75]:
  # model evaluation for testing set
  mae1 = metrics.mean_absolute_error(y_test, y_pred1)
  mse1 = metrics.mean_squared_error(y_test, y_pred1)
  r21 = metrics.r2_score(y_test, y_pred1)

In [76]:
print("The model performance for testing set")
print("--------------------------------------")
print('MAE is {}'.format(mae1))
print('MSE is {}'.format(mse1))
print('R2 score is {}'.format(r21))

The model performance for testing set
--------------------------------------
MAE is 16.396614889243313
MSE is 704.4230216162632
R2 score is 0.516841157626702


In [77]:
  # model evaluation for training set
maeTrain1 = metrics.mean_absolute_error(y_train, y_pred_train1)
mseTrain1 = metrics.mean_squared_error(y_train, y_pred_train1)
r2Train1 = metrics.r2_score(y_train, y_pred_train1)

In [78]:
print("The model performance for training set")
print("--------------------------------------")
print('MAE is {}'.format(maeTrain1))
print('MSE is {}'.format(mseTrain1))
print('R2 score is {}'.format(r2Train1))

The model performance for training set
--------------------------------------
MAE is 4.884987199304926
MSE is 134.70600983120872
R2 score is 0.9487899432780524


In [79]:
cvscoretrain1 = (cross_val_score(regressor1,x_train,y_train.ravel(),cv=5).mean())

In [80]:
print("The CV score for training set")
print("--------------------------------------")
print (cross_val_score(regressor1,x_train,y_train.ravel(),cv=5))
print('Q2 is {}'.format(cvscoretrain1))

The CV score for training set
--------------------------------------
[0.23377748 0.34519911 0.50343776 0.75085777 0.51862517]
Q2 is 0.47037945760692657


In [81]:
## model evaluation for extest set
maeex1 = metrics.mean_absolute_error(y_extest, y_pred_extest1)
mseex1 = metrics.mean_squared_error(y_extest, y_pred_extest1)
r2ex1 = metrics.r2_score(y_extest, y_pred_extest1)

In [82]:
print("The model performance for extest set")
print("--------------------------------------")
print('MAE is {}'.format(maeex1))
print('MSE is {}'.format(mseex1))
print('R2 score is {}'.format(r2ex1))

The model performance for extest set
--------------------------------------
MAE is 22.283648968062636
MSE is 1148.993934759279
R2 score is 0.5975806401227395


In [83]:
## model evaluation for val set
maevl1 = metrics.mean_absolute_error(y_val, y_pred_val1)
msevl1 = metrics.mean_squared_error(y_val, y_pred_val1)
r2vl1 = metrics.r2_score(y_val, y_pred_val1)

In [84]:
print("The model performance for val set")
print("--------------------------------------")
print('MAE is {}'.format(maevl1))
print('MSE is {}'.format(msevl1))
print('R2 score is {}'.format(r2vl1))

The model performance for val set
--------------------------------------
MAE is 19.687832093019768
MSE is 855.5491031335837
R2 score is 0.7463171675130214


In [85]:
## model evaluation for model set
maemod1 = metrics.mean_absolute_error(y_model, y_pred_model1)
msemod1 = metrics.mean_squared_error(y_model, y_pred_model1)
r2mod1 = metrics.r2_score(y_model, y_pred_model1)

In [86]:
print("The model performance for model set")
print("--------------------------------------")
print('MAE is {}'.format(maemod1))
print('MSE is {}'.format(msemod1))
print('R2 score is {}'.format(r2mod1))

The model performance for model set
--------------------------------------
MAE is 8.853149616827485
MSE is 329.3414170220389
R2 score is 0.8729654237861997


In [87]:
# cv for modeling set 
cvscoremod1 = (cross_val_score(regressor1,x_model,y_model.ravel(),cv=5).mean())

In [88]:
print("The CV score for model set")
print("--------------------------------------")
print (cross_val_score(regressor1,x_model,y_model.ravel(),cv=5))
print('Q2 is {}'.format(cvscoremod1))

The CV score for model set
--------------------------------------
[0.72544515 0.42267191 0.56496837 0.51122386 0.76314523]
Q2 is 0.5974909028895093
