In [1]:
# Import Section
import csv
import codecs
import sys
import io
import numpy as np
import pandas as pd
import scipy as sp

# For Regression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from statistics import mean

from sklearn.preprocessing import StandardScaler


from sklearn.linear_model import LinearRegression
from sklearn import tree
from sklearn import linear_model
from sklearn.linear_model import ElasticNet
from sklearn.kernel_ridge import KernelRidge

# Python script for confusion matrix creation. 
from sklearn.metrics import *
from numpy import mean
from numpy import std
from sklearn import metrics

In [94]:
dataset=pd.read_excel("1056_DES_808.xlsx",index_col=0)

In [95]:
dataset.shape

(1056, 809)

In [96]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1056 entries, 1Co to 1056
Columns: 809 entries, apol to Act
dtypes: float64(720), int64(89)
memory usage: 6.5+ MB


In [97]:
# to check the null values 
dataset.isnull().sum()

apol          0
nAtom         0
nHeavyAtom    0
nH            0
nC            0
             ..
RDF140i       0
RDF145i       0
RDF150i       0
RDF155i       0
Act           0
Length: 809, dtype: int64

In [98]:
dataset.isnull().count()

apol          1056
nAtom         1056
nHeavyAtom    1056
nH            1056
nC            1056
              ... 
RDF140i       1056
RDF145i       1056
RDF150i       1056
RDF155i       1056
Act           1056
Length: 809, dtype: int64

In [99]:
#independent and dependent features
x = dataset.drop(['Act'],axis=1)
y = dataset['Act']

In [100]:
x

apol  nAtom  nHeavyAtom  nH  nC  nN  nO  nF  nCl  nBr  ...  \
Name                                                               ...   
1Co   133.165685    101          56  45  50   3   0   0    2    0  ...   
2Co   139.352857    107          58  49  52   3   0   0    2    0  ...   
3Co   145.540029    113          60  53  54   3   0   0    2    0  ...   
4Co   136.259271    104          57  47  51   3   0   0    2    0  ...   
5Co   142.446443    110          59  51  53   3   0   0    2    0  ...   
...          ...    ...         ...  ..  ..  ..  ..  ..  ...  ...  ...   
1052  188.369475    151          76  75  70   3   0   0    2    0  ...   
1053   98.764169     74          41  33  35   3   0   0    2    0  ...   
1054  104.951341     80          43  37  37   3   0   0    2    0  ...   
1055  111.138513     86          45  41  39   3   0   0    2    0  ...   
1056  101.857755     77          42  35  36   3   0   0    2    0  ...   

         RDF110i     RDF115i     RDF120i     RDF125i     RDF130i  \
Name                                                               
1Co    45.156253   59.676515   24.173201   17.214804    6.981186   
2Co    68.000307   57.900928   41.939084   20.980707   15.963666   
3Co    69.859802   73.222593   34.083616   31.464396   18.153969   
4Co    59.016271   69.164208   36.837770   24.299923   16.386682   
5Co    70.042496   74.048574   50.203719   27.390293   19.871290   
...          ...         ...         ...         ...         ...   
1052  196.666997  144.530929  156.169774  122.956393  124.190178   
1053   20.402330   13.207864    5.324045    1.363065    2.555885   
1054   26.788661   18.848139   10.929213    5.351403    5.335048   
1055   27.417855   26.845085   17.331248    6.476668    4.004508   
1056   27.226488   21.669977   14.169193    6.843099    8.844587   

           RDF135i       RDF140i       RDF145i        RDF150i        RDF155i  
Name                                                                          
1Co   1.365999e+00  1.626969e+00  4.790000e-06   2.460000e-32   2.440000e-80  
2Co   5.881577e+00  3.621614e-01  1.427485e+00   8.570000e-11   9.920000e-43  
3Co   5.034062e+00  1.658429e+00  4.790000e-06   2.460000e-32   2.440000e-80  
4Co   5.462919e+00  4.920207e+00  5.860128e+00   1.626151e+00   1.121483e+00  
5Co   1.107855e+01  5.203310e+00  1.191608e+00   1.256458e+00   1.456740e+00  
...            ...           ...           ...            ...            ...  
1052  1.187171e+02  1.048155e+02  7.590655e+01   7.433105e+01   5.405252e+01  
1053  4.440000e-07  9.270000e-35  3.730000e-84  2.900000e-155  4.350000e-248  
1054  8.417984e-01  2.380000e-07  2.240000e-35   4.070000e-85  1.430000e-156  
1055  1.364400e+00  2.500000e-10  8.860000e-42   6.050000e-95  7.970000e-170  
1056  3.355629e+00  7.972980e-01  2.820000e-07   3.290000e-35   7.420000e-85  

[1056 rows x 808 columns]

In [101]:
y

Name
1Co      85.3
2Co      98.7
3Co      77.3
4Co      76.0
5Co      89.3
        ...  
1052     37.0
1053    102.0
1054     83.2
1055     70.1
1056    109.0
Name: Act, Length: 1056, dtype: float64

In [102]:
x.shape

(1056, 808)

In [103]:
print(type(x))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [104]:
# scealing is required for indepandent variables at ANN
scale = StandardScaler()
X1 = scale.fit_transform(x)

In [105]:
## to overcome the problem input contains nan infinity or a value too large for dtype('float64').
## We need to cinvert the pandas dataframe to numpy array 
X = np.nan_to_num(X1)
Y = np.nan_to_num(y)

In [106]:
X

array([[ 0.48049996,  0.48377271,  0.44222646, ..., -0.42590324,
        -0.39328391, -0.35184376],
       [ 0.63174753,  0.66616984,  0.55142584, ..., -0.36957763,
        -0.39328391, -0.35184376],
       [ 0.78299509,  0.84856698,  0.66062522, ..., -0.42590324,
        -0.39328391, -0.35184376],
       ...,
       [-0.20920947, -0.15461727, -0.2675695 , ..., -0.42590342,
        -0.39328391, -0.35184376],
       [-0.0579619 ,  0.02777987, -0.15837012, ..., -0.42590342,
        -0.39328391, -0.35184376],
       [-0.28483325, -0.24581584, -0.32216919, ..., -0.42590341,
        -0.39328391, -0.35184376]])

In [107]:
Y

array([ 85.3,  98.7,  77.3, ...,  83.2,  70.1, 109. ])

In [108]:
Y.shape

(1056,)

In [109]:
x_model, x_extest, y_model, y_extest = train_test_split(X,Y,test_size=.2, random_state = 7000, shuffle=True)

In [110]:
x_model.shape

(844, 808)

In [111]:
x_train, x_test2, y_train, y_test2 = train_test_split(x_model,y_model,test_size=.2, random_state = 7000, shuffle=True)

In [112]:
x_train.shape

(675, 808)

In [113]:
x_test2.shape

(169, 808)

In [114]:
x_val, x_test, y_val, y_test = train_test_split(x_test2,y_test2,test_size=.5, random_state = 7000, shuffle=True)

In [115]:
x_test.shape

(85, 808)

In [116]:
x_val.shape

(84, 808)

In [117]:
regressor = LinearRegression(fit_intercept=True,
    normalize=False,
    copy_X=True,
    n_jobs=-1,
    positive=False)

In [118]:
 regressor.fit(x_train, y_train)

LinearRegression(n_jobs=-1)

In [119]:
# compute the testing accuracy
y_pred = regressor.predict(x_test)

In [120]:
y_pred_train = regressor.predict(x_train)

In [121]:
y_pred_train.shape

(675,)

In [122]:
y_pred_val = regressor.predict(x_val)

In [123]:
y_pred_extest = regressor.predict(x_extest)

In [124]:
y_pred_model = regressor.predict(x_model)

In [125]:
  print("\n")
  print("overall Performance: ", )



overall Performance: 


In [126]:
  # model evaluation for testing set
  mae = metrics.mean_absolute_error(y_test, y_pred)
  mse = metrics.mean_squared_error(y_test, y_pred)
  r2 = metrics.r2_score(y_test, y_pred)

In [127]:
print("The model performance for testing set")
print("--------------------------------------")
print('MAE is {}'.format(mae))
print('MSE is {}'.format(mse))
print('R2 score is {}'.format(r2))

The model performance for testing set
--------------------------------------
MAE is 446.5566150813171
MSE is 4199945.162639347
R2 score is -1859.0918057302495


In [128]:
  # model evaluation for training set
maeTrain = metrics.mean_absolute_error(y_train, y_pred_train)
mseTrain = metrics.mean_squared_error(y_train, y_pred_train)
r2Train = metrics.r2_score(y_train, y_pred_train)

In [129]:
print("The model performance for training set")
print("--------------------------------------")
print('MAE is {}'.format(maeTrain))
print('MSE is {}'.format(mseTrain))
print('R2 score is {}'.format(r2Train))

The model performance for training set
--------------------------------------
MAE is 5.2085827559436685e-11
MSE is 4.5352150384523715e-21
R2 score is 1.0


In [130]:
cvscoretrain = (-cross_val_score(regressor,x_train,y_train.ravel(),cv=5).mean())

In [131]:
print("The CV score for training set")
print("--------------------------------------")
print (-cross_val_score(regressor,x_train,y_train.ravel(),cv=5))
print('Q2 is {}'.format(cvscoretrain))

The CV score for training set
--------------------------------------
[13.73387141 86.9686676  72.46510458 22.53955949  8.25102342]
Q2 is 40.79164530039665


In [132]:
## model evaluation for extest set
maeex = metrics.mean_absolute_error(y_extest, y_pred_extest)
mseex = metrics.mean_squared_error(y_extest, y_pred_extest)
r2ex = metrics.r2_score(y_extest, y_pred_extest)

In [133]:
print("The model performance for extest set")
print("--------------------------------------")
print('MAE is {}'.format(maeex))
print('MSE is {}'.format(mseex))
print('R2 score is {}'.format(r2ex))

The model performance for extest set
--------------------------------------
MAE is 386.9365677304716
MSE is 2961141.615912762
R2 score is -1195.4625759206385


In [134]:
## model evaluation for val set
maevl = metrics.mean_absolute_error(y_val, y_pred_val)
msevl = metrics.mean_squared_error(y_val, y_pred_val)
r2vl = metrics.r2_score(y_val, y_pred_val)

In [135]:
print("The model performance for val set")
print("--------------------------------------")
print('MAE is {}'.format(maevl))
print('MSE is {}'.format(msevl))
print('R2 score is {}'.format(r2vl))

The model performance for val set
--------------------------------------
MAE is 350.01953482874933
MSE is 808436.1422151913
R2 score is -443.03371335257594


In [136]:
## model evaluation for model set
maemod = metrics.mean_absolute_error(y_model, y_pred_model)
msemod = metrics.mean_squared_error(y_model, y_pred_model)
r2mod = metrics.r2_score(y_model, y_pred_model)

In [137]:
print("The model performance for model set")
print("--------------------------------------")
print('MAE is {}'.format(maemod))
print('MSE is {}'.format(msemod))
print('R2 score is {}'.format(r2mod))

The model performance for model set
--------------------------------------
MAE is 79.80918626488376
MSE is 503440.7284009722
R2 score is -215.20968731622986


In [138]:
# cv for modeling set 
cvscoremod = (-cross_val_score(regressor,x_model,y_model.ravel(),cv=5).mean())

In [139]:
print("The CV score for model set")
print("--------------------------------------")
print (-cross_val_score(regressor,x_model,y_model.ravel(),cv=5))
print('Q2 is {}'.format(cvscoremod))

The CV score for model set
--------------------------------------
[323.08911113 610.16014958 789.13438146 557.8278974   94.9624768 ]
Q2 is 475.0348032724357
