In [1]:
# Import Section
import csv
import codecs
import sys
import io
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('seaborn')

# For Regression
from sklearn.cross_decomposition import PLSRegression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from statistics import mean

#Data standarization 
from sklearn.preprocessing import StandardScaler

# Python script for confusion matrix creation. 
from sklearn.metrics import *
from numpy import mean
from numpy import std
from sklearn import metrics 

In [2]:
dataset=pd.read_excel("1056_DES_169-134.xlsx",index_col=0)

In [3]:
dataset.head()

apol  nF  nCl        ATS0m        ATS1m      AATS0m      AATS3v  \
Name                                                                          
1Co   133.165685   0    2  13834.04355  15855.04115  136.970728  252.864348   
2Co   139.352857   0    2  14126.63605  16191.99774  132.024636  244.481402   
3Co   145.540029   0    2  14419.22855  16528.95434  127.603792  240.647657   
4Co   136.259271   0    2  13980.33980  16023.51944  134.426344  252.693531   
5Co   142.446443   0    2  14272.93230  16360.47604  129.753930  244.504666   

          AATS5v      AATS7v    AATS6e  ...     TDB1e   MOMI-XY   MOMI-XZ  \
Name                                    ...                                 
1Co   247.524744  221.438168  7.521599  ...  9.530320  1.146427  1.345100   
2Co   245.418467  212.569484  7.504751  ...  9.413584  1.171703  1.386001   
3Co   243.554058  206.932170  7.489908  ...  9.566299  1.185583  1.413948   
4Co   246.313314  223.976928  7.498352  ...  9.535809  1.134459  1.399720   
5Co   245.443478  209.459975  7.492760  ...  9.374899  1.154371  1.429966   

      geomShape     RDF10u     RDF20m     RDF35m     RDF40m     RDF45m   Act  
Name                                                                          
1Co    0.712301  38.306496  10.949330  34.961509  39.173554  57.903677  85.3  
2Co    0.783592  35.009162  12.615265  29.023582  57.104934  68.424443  98.7  
3Co    0.712301  34.521511  10.763313  38.544967  41.524399  63.396066  77.3  
4Co    0.869555  37.952259  10.799773  35.038023  39.350639  57.949184  76.0  
5Co    0.905091  37.414481  12.841396  28.883633  57.271310  68.532256  89.3  

[5 rows x 135 columns]

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1056 entries, 1Co to 1056
Columns: 135 entries, apol to Act
dtypes: float64(122), int64(13)
memory usage: 1.1+ MB


In [5]:
dataset.shape

(1056, 135)

In [6]:
# to check the null values 
dataset.isnull().sum()

apol      0
nF        0
nCl       0
ATS0m     0
ATS1m     0
         ..
RDF20m    0
RDF35m    0
RDF40m    0
RDF45m    0
Act       0
Length: 135, dtype: int64

In [7]:
dataset.isnull().count()

apol      1056
nF        1056
nCl       1056
ATS0m     1056
ATS1m     1056
          ... 
RDF20m    1056
RDF35m    1056
RDF40m    1056
RDF45m    1056
Act       1056
Length: 135, dtype: int64

In [8]:
x = dataset.drop(['Act'],axis=1)
y = dataset['Act']

In [9]:
x

apol  nF  nCl        ATS0m        ATS1m      AATS0m      AATS3v  \
Name                                                                          
1Co   133.165685   0    2  13834.04355  15855.04115  136.970728  252.864348   
2Co   139.352857   0    2  14126.63605  16191.99774  132.024636  244.481402   
3Co   145.540029   0    2  14419.22855  16528.95434  127.603792  240.647657   
4Co   136.259271   0    2  13980.33980  16023.51944  134.426344  252.693531   
5Co   142.446443   0    2  14272.93230  16360.47604  129.753930  244.504666   
...          ...  ..  ...          ...          ...         ...         ...   
1052  188.369475   0    2  16749.80789  19824.85681  110.925880  202.581103   
1053   98.764169   0    2  11657.88897  13257.26603  157.539040  261.802038   
1054  104.951341   0    2  11950.48146  13594.22263  149.381018  249.842182   
1055  111.138513   0    2  12243.07396  13931.17922  142.361325  244.402278   
1056  101.857755   0    2  11804.18522  13425.74433  153.301107  261.288743   

          AATS5v      AATS7v    AATS6e  ...        TDB9v     TDB1e   MOMI-XY  \
Name                                    ...                                    
1Co   247.524744  221.438168  7.521599  ...  1420.146387  9.530320  1.146427   
2Co   245.418467  212.569484  7.504751  ...  1427.993118  9.413584  1.171703   
3Co   243.554058  206.932170  7.489908  ...  1425.197977  9.566299  1.185583   
4Co   246.313314  223.976928  7.498352  ...  1424.622362  9.535809  1.134459   
5Co   245.443478  209.459975  7.492760  ...  1430.931966  9.374899  1.154371   
...          ...         ...       ...  ...          ...       ...       ...   
1052  241.721383  203.050385  7.461727  ...  1367.913810  9.481667  1.057297   
1053  230.436721  195.547545  7.568652  ...  1204.019980  9.664277  1.119573   
1054  229.042168  186.197547  7.540159  ...  1253.685574  9.714047  1.114074   
1055  227.853579  181.635464  7.516364  ...  1268.389586  9.486820  1.123937   
1056  229.369101  200.064913  7.531769  ...  1227.217268  9.601583  1.093534   

       MOMI-XZ  geomShape     RDF10u     RDF20m     RDF35m     RDF40m  \
Name                                                                    
1Co   1.345100   0.712301  38.306496  10.949330  34.961509  39.173554   
2Co   1.386001   0.783592  35.009162  12.615265  29.023582  57.104934   
3Co   1.413948   0.712301  34.521511  10.763313  38.544967  41.524399   
4Co   1.399720   0.869555  37.952259  10.799773  35.038023  39.350639   
5Co   1.429966   0.905091  37.414481  12.841396  28.883633  57.271310   
...        ...        ...        ...        ...        ...        ...   
1052  2.498228   0.859835  51.771651  13.017378  34.433252  62.417671   
1053  1.843038   0.728620  23.243882   8.726441  26.322960  63.526212   
1054  1.855175   0.793484  20.467464   8.575839  25.780400  64.422742   
1055  1.857902   0.783088  31.204761   9.706272  28.851241  67.833494   
1056  1.936862   0.821660  25.436853   8.893778  26.209583  63.734824   

         RDF45m  
Name             
1Co   57.903677  
2Co   68.424443  
3Co   63.396066  
4Co   57.949184  
5Co   68.532256  
...         ...  
1052  87.048901  
1053  49.522226  
1054  51.285834  
1055  57.363132  
1056  49.628820  

[1056 rows x 134 columns]

In [10]:
## to overcome the problem input contains nan infinity or a value too large for dtype('float64').
## We need to cinvert the pandas dataframe to numpy array as pe rrequirements of the model 
X = np.nan_to_num(x)
Y = np.nan_to_num(y)

In [11]:
X

array([[133.165685  ,   0.        ,   2.        , ...,  34.96150938,
         39.17355402,  57.90367691],
       [139.352857  ,   0.        ,   2.        , ...,  29.02358183,
         57.10493384,  68.42444301],
       [145.540029  ,   0.        ,   2.        , ...,  38.54496663,
         41.52439881,  63.39606608],
       ...,
       [104.951341  ,   0.        ,   2.        , ...,  25.78039954,
         64.42274238,  51.28583444],
       [111.138513  ,   0.        ,   2.        , ...,  28.85124132,
         67.83349448,  57.36313181],
       [101.857755  ,   0.        ,   2.        , ...,  26.20958306,
         63.73482397,  49.62882001]])

In [12]:
Y

array([ 85.3,  98.7,  77.3, ...,  83.2,  70.1, 109. ])

In [13]:
x_model, x_extest, y_model, y_extest = train_test_split(X,Y,test_size=.2, random_state = 7000, shuffle=True)

In [14]:
x_model.shape

(844, 134)

In [15]:
x_train, x_test2, y_train, y_test2 = train_test_split(x_model,y_model,test_size=.3, random_state = 7000, shuffle=True)

In [16]:
x_train.shape

(590, 134)

In [17]:
x_test2.shape

(254, 134)

In [18]:
x_val, x_test, y_val, y_test = train_test_split(x_test2,y_test2,test_size=.5, random_state = 7000, shuffle=True)

In [19]:
x_test.shape

(127, 134)

In [20]:
x_val.shape

(127, 134)

In [21]:
# scealing is required and the PLS has inbuild scealer, so no need to use extra sealer 
#scale = StandardScaler()

In [88]:
regressor = PLSRegression(n_components=6,
                    scale=True,
                    max_iter=300,
                    tol=1e-06,
                    copy=True,)

In [89]:
#PLSRegression?

In [90]:
regressor.fit(x_train, y_train)

PLSRegression(max_iter=300, n_components=6)

In [91]:
print(f"PLS r-squared for test {regressor.score(x_test, y_test):.3f}")

PLS r-squared for test 0.312


In [92]:
# compute the testing accuracy
y_pred = regressor.predict(x_test)

In [93]:
y_pred_train = regressor.predict(x_train)

In [94]:
y_pred_train.shape

(590, 1)

In [95]:
y_pred_val = regressor.predict(x_val)

In [96]:
y_pred_extest = regressor.predict(x_extest)

In [97]:
y_pred_model = regressor.predict(x_model)

In [98]:
y_pred_all = regressor.predict(X)

In [99]:
  print("\n")
  print("overall Performance: ", )



overall Performance: 


In [100]:
  # model evaluation for testing set
  mae = metrics.mean_absolute_error(y_test, y_pred)
  mse = metrics.mean_squared_error(y_test, y_pred)
  r2 = metrics.r2_score(y_test, y_pred)

In [101]:
print("The model performance for testing set")
print("--------------------------------------")
print('MAE is {}'.format(mae))
print('MSE is {}'.format(mse))
print('R2 score is {}'.format(r2))

The model performance for testing set
--------------------------------------
MAE is 32.07062367283611
MSE is 1839.6138244994063
R2 score is 0.3118450778771492


In [102]:
  # model evaluation for training set
maeTrain = metrics.mean_absolute_error(y_train, y_pred_train)
mseTrain = metrics.mean_squared_error(y_train, y_pred_train)
r2Train = metrics.r2_score(y_train, y_pred_train)

In [103]:
print("The model performance for training set")
print("--------------------------------------")
print('MAE is {}'.format(maeTrain))
print('MSE is {}'.format(mseTrain))
print('R2 score is {}'.format(r2Train))

The model performance for training set
--------------------------------------
MAE is 26.77496439449338
MSE is 1256.243341568353
R2 score is 0.46532660254795855


In [104]:
#CV score for training set
cvscoretra = (cross_val_score(regressor,x_train,y_train.ravel(),cv=5).mean())

In [105]:
print("The CV score for training set")
print("--------------------------------------")
print (cross_val_score(regressor,x_train,y_train.ravel(),cv=5))
print('Q2 is {}'.format(cvscoretra))

The CV score for training set
--------------------------------------
[0.40542038 0.36674045 0.37526181 0.27063396 0.39764119]
Q2 is 0.36313955656280755


In [106]:
## model evaluation for extest set
maeex = metrics.mean_absolute_error(y_extest, y_pred_extest)
mseex = metrics.mean_squared_error(y_extest, y_pred_extest)
r2ex = metrics.r2_score(y_extest, y_pred_extest)

In [107]:
print("The model performance for extest set")
print("--------------------------------------")
print('MAE is {}'.format(maeex))
print('MSE is {}'.format(mseex))
print('R2 score is {}'.format(r2ex))

The model performance for extest set
--------------------------------------
MAE is 30.029874795121067
MSE is 1699.361541461496
R2 score is 0.31336533302182024


In [108]:
## model evaluation for val set
maevl = metrics.mean_absolute_error(y_val, y_pred_val)
msevl = metrics.mean_squared_error(y_val, y_pred_val)
r2vl = metrics.r2_score(y_val, y_pred_val)

In [109]:
print("The model performance for val set")
print("--------------------------------------")
print('MAE is {}'.format(maevl))
print('MSE is {}'.format(msevl))
print('R2 score is {}'.format(r2vl))

The model performance for val set
--------------------------------------
MAE is 26.608176443275358
MSE is 1196.7688839054456
R2 score is 0.3581304553409118


In [110]:
## model evaluation for modeling set
maemod = metrics.mean_absolute_error(y_model, y_pred_model)
msemod = metrics.mean_squared_error(y_model, y_pred_model)
r2mod = metrics.r2_score(y_model, y_pred_model)

In [111]:
print("The model performance for modeling set")
print("--------------------------------------")
print('MAE is {}'.format(maemod))
print('MSE is {}'.format(msemod))
print('R2 score is {}'.format(r2mod))

The model performance for modeling set
--------------------------------------
MAE is 27.546725838266884
MSE is 1335.0760373136784
R2 score is 0.42663285609050416


In [112]:
#CV score for modeling set
cvscoremod = (cross_val_score(regressor,x_model,y_model.ravel(),cv=5).mean())

In [113]:
print("The CV score for Modeling set")
print("--------------------------------------")
print (cross_val_score(regressor,x_model,y_model.ravel(),cv=5))
print('Q2 is {}'.format(cvscoremod))

The CV score for Modeling set
--------------------------------------
[0.4250271  0.31895663 0.23944264 0.28612864 0.44052732]
Q2 is 0.34201646728020646


In [114]:
#Randomize search CV
from sklearn.model_selection import RandomizedSearchCV

In [50]:
n_components =[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 
              31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 
              60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 
              88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
              113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134]
scale = ['True', 'False']
max_iter = [200, 300, 500]
copy = ['True', 'False']

In [51]:
# creatting parameter gride
param_grid_regressor= {'n_components': n_components ,
                       'scale':scale, 'max_iter': max_iter, 'copy': copy}

In [52]:
print (param_grid_regressor)

{'n_components': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134], 'scale': ['True', 'False'], 'max_iter': [200, 300, 500], 'copy': ['True', 'False']}


In [53]:
regressor_random = RandomizedSearchCV(estimator = regressor, param_distributions=param_grid_regressor, n_iter = 100,
                              cv = 5, verbose =2,
                              n_jobs= -1, scoring = 'neg_mean_squared_error' )

In [54]:
regressor_random.fit (x_train,y_train)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


RandomizedSearchCV(cv=5, estimator=PLSRegression(n_components=134), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'copy': ['True', 'False'],
                                        'max_iter': [200, 300, 500],
                                        'n_components': [1, 2, 3, 4, 5, 6, 7, 8,
                                                         9, 10, 11, 12, 13, 14,
                                                         15, 16, 17, 18, 19, 20,
                                                         21, 22, 23, 24, 25, 26,
                                                         27, 28, 29, 30, ...],
                                        'scale': ['True', 'False']},
                   scoring='neg_mean_squared_error', verbose=2)

In [55]:
regressor_random.best_params_

{'scale': 'True', 'n_components': 6, 'max_iter': 300, 'copy': 'True'}

In [56]:
regressor_random.best_score_

-1477.0258617445766

In [57]:
# parameter tuning grid searchCV
from sklearn.model_selection import GridSearchCV

In [58]:
regressor_grid = GridSearchCV(estimator =regressor, param_grid=param_grid_regressor,
                              cv = 5, verbose =2,
                              n_jobs= -1,  scoring = "neg_mean_squared_error")

regressor_grid.fit (x_train,y_train)

Fitting 5 folds for each of 1608 candidates, totalling 8040 fits


GridSearchCV(cv=5, estimator=PLSRegression(n_components=134), n_jobs=-1,
             param_grid={'copy': ['True', 'False'], 'max_iter': [200, 300, 500],
                         'n_components': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                          13, 14, 15, 16, 17, 18, 19, 20, 21,
                                          22, 23, 24, 25, 26, 27, 28, 29, 30, ...],
                         'scale': ['True', 'False']},
             scoring='neg_mean_squared_error', verbose=2)

In [59]:
regressor_grid.best_params_

{'copy': 'True', 'max_iter': 200, 'n_components': 7, 'scale': 'True'}

In [60]:
regressor_grid.best_score_

-1474.2078464523638