In [1]:
# Import Section
import csv
import codecs
import sys
import io
import numpy as np
import pandas as pd
import scipy as sp

# For Regression
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from statistics import mean

from sklearn import svm

# Python script for confusion matrix creation. 
from sklearn.metrics import *
from numpy import mean
from numpy import std
from sklearn import metrics

In [2]:
dataset=pd.read_csv("data_294.csv")

In [3]:
dataset.shape

(294, 17)

In [4]:
x = dataset[['1', '15', '18', '21', '25', '26', '39', '41', '58', '69', '83', '85', '141', '155', '166']]

In [5]:
x.shape

(294, 15)

In [6]:
y = dataset['Act']

In [7]:
x_model, x_extest, y_model, y_extest = train_test_split(x,y,test_size=.2, random_state = 7000, shuffle=True)

In [8]:
x_model.shape

(235, 15)

In [9]:
x_train, x_test2, y_train, y_test2 = train_test_split(x_model,y_model,test_size=.3, random_state = 7000, shuffle=True)

In [10]:
x_train.shape

(164, 15)

In [11]:
x_test2.shape

(71, 15)

In [12]:
x_val, x_test, y_val, y_test = train_test_split(x_test2,y_test2,test_size=.5, random_state = 7000, shuffle=True)

In [13]:
x_test.shape

(36, 15)

In [14]:
x_val.shape

(35, 15)

In [15]:
# scealing is required for indepandent variables at ANN
from sklearn.preprocessing import StandardScaler

In [16]:
scale = StandardScaler()

In [17]:
X = scale.fit_transform(x)
X_train = scale.fit_transform(x_train)
X_test = scale.fit_transform(x_test)
X_val = scale.fit_transform(x_val)
X_model = scale.fit_transform(x_model)
X_extest = scale.fit_transform(x_extest)

In [18]:
regressor = svm.SVR(kernel='rbf',
    degree=1,
    gamma='scale',
    coef0=0.0,
    tol=0.001,
    C=100,
    epsilon=4,)

In [19]:
 regressor.fit(X_train, y_train)

SVR(C=100, degree=1, epsilon=4)

In [20]:
# compute the testing accuracy
y_pred = regressor.predict(X_test)

In [21]:
y_pred_train = regressor.predict(X_train)

In [22]:
y_pred_train.shape

(164,)

In [23]:
y_pred_val = regressor.predict(X_val)

In [24]:
y_pred_extest = regressor.predict(X_extest)

In [25]:
y_pred_model = regressor.predict(X_model)

In [26]:
y_pred_all = regressor.predict(X)

In [27]:
  print("\n")
  print("overall Performance: ", )



overall Performance: 


In [28]:
  # model evaluation for testing set
  mae = metrics.mean_absolute_error(y_test, y_pred)
  mse = metrics.mean_squared_error(y_test, y_pred)
  r2 = metrics.r2_score(y_test, y_pred)

In [29]:
print("The model performance for testing set")
print("--------------------------------------")
print('MAE is {}'.format(mae))
print('MSE is {}'.format(mse))
print('R2 score is {}'.format(r2))

The model performance for testing set
--------------------------------------
MAE is 14.39280631675118
MSE is 490.71699000794916
R2 score is 0.6634206356840111


In [30]:
  # model evaluation for training set
maeTrain = metrics.mean_absolute_error(y_train, y_pred_train)
mseTrain = metrics.mean_squared_error(y_train, y_pred_train)
r2Train = metrics.r2_score(y_train, y_pred_train)

In [31]:
print("The model performance for training set")
print("--------------------------------------")
print('MAE is {}'.format(maeTrain))
print('MSE is {}'.format(mseTrain))
print('R2 score is {}'.format(r2Train))

The model performance for training set
--------------------------------------
MAE is 14.442688052644227
MSE is 689.3727520264391
R2 score is 0.7379269285900852


In [32]:
cvscoretrain = (-cross_val_score(regressor,X_train,y_train.ravel(),cv=5).mean())

In [33]:
print("The CV score for training dataset")
print("--------------------------------------")
print (-cross_val_score(regressor,X_train,y_train.ravel(),cv=5))
print('Q2 is {}'.format(cvscoretrain))

The CV score for training dataset
--------------------------------------
[-0.52396645 -0.49055031 -0.5452224  -0.75533647 -0.53213977]
Q2 is -0.5694430801244567


In [34]:
## model evaluation for extest set
maeex = metrics.mean_absolute_error(y_extest, y_pred_extest)
mseex = metrics.mean_squared_error(y_extest, y_pred_extest)
r2ex = metrics.r2_score(y_extest, y_pred_extest)

In [35]:
print("The model performance for extest set")
print("--------------------------------------")
print('MAE is {}'.format(maeex))
print('MSE is {}'.format(mseex))
print('R2 score is {}'.format(r2ex))

The model performance for extest set
--------------------------------------
MAE is 15.13070273341446
MSE is 556.1716836290016
R2 score is 0.8052084992470118


In [36]:
## model evaluation for val set
maevl = metrics.mean_absolute_error(y_val, y_pred_val)
msevl = metrics.mean_squared_error(y_val, y_pred_val)
r2vl = metrics.r2_score(y_val, y_pred_val)

In [37]:
print("The model performance for val set")
print("--------------------------------------")
print('MAE is {}'.format(maevl))
print('MSE is {}'.format(msevl))
print('R2 score is {}'.format(r2vl))

The model performance for val set
--------------------------------------
MAE is 18.205263778276088
MSE is 700.4780721367499
R2 score is 0.792297998111602


In [38]:
## model evaluation for modeling  dataset
maemod = metrics.mean_absolute_error(y_model, y_pred_model)
msemod = metrics.mean_squared_error(y_model, y_pred_model)
r2mod = metrics.r2_score(y_model, y_pred_model)

In [39]:
print("The model performance for modeling set")
print("--------------------------------------")
print('MAE is {}'.format(maemod))
print('MSE is {}'.format(msemod))
print('R2 score is {}'.format(r2mod))

The model performance for modeling set
--------------------------------------
MAE is 14.353534339243414
MSE is 642.156998847856
R2 score is 0.7523052431455826


In [40]:
cvscoremod = (-cross_val_score(regressor,X_model,y_model.ravel(),cv=5).mean())

In [41]:
print("The CV score for modeling dataset")
print("--------------------------------------")
print (-cross_val_score(regressor,X_model,y_model.ravel(),cv=5))
print('Q2 is {}'.format(cvscoremod))

The CV score for modeling dataset
--------------------------------------
[-0.828682   -0.5557068  -0.56827264 -0.52463842 -0.78400277]
Q2 is -0.6522605272610681


In [230]:
svm.SVR??

In [155]:
# creatting parameter gride
param_grid_regressor = {'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 
                        'gamma': ['scale', 'auto'], 'C': [0.1, 1, 10, 100,150,200], 
                        'epsilon': [0.1, 1, 2, 4, 6, 10, 15, 20], 'degree' : [1,2,3,4,5,6, 7, 8]}

In [156]:
print (param_grid_regressor)
                    

{'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'gamma': ['scale', 'auto'], 'C': [0.1, 1, 10, 100, 150, 200], 'epsilon': [0.1, 1, 2, 4, 6, 10, 15, 20], 'degree': [1, 2, 3, 4, 5, 6, 7, 8]}


In [157]:
regressor1 = svm.SVR()

In [158]:
#Randomize search CV
from sklearn.model_selection import RandomizedSearchCV

In [159]:
regressor_random = RandomizedSearchCV(estimator = regressor1, param_distributions=param_grid_regressor, n_iter = 100,
                              cv = 5, verbose =2,
                              n_jobs= -1, scoring = 'neg_mean_squared_error' )

In [160]:
regressor_random.fit (X_model,y_model)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


RandomizedSearchCV(cv=5, estimator=SVR(), n_iter=100, n_jobs=-1,
                   param_distributions={'C': [0.1, 1, 10, 100, 150, 200],
                                        'degree': [1, 2, 3, 4, 5, 6, 7, 8],
                                        'epsilon': [0.1, 1, 2, 4, 6, 10, 15,
                                                    20],
                                        'gamma': ['scale', 'auto'],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']},
                   scoring='neg_mean_squared_error', verbose=2)

In [161]:
regressor_random.best_params_

{'kernel': 'rbf', 'gamma': 'scale', 'epsilon': 4, 'degree': 3, 'C': 200}

In [162]:
regressor_random.best_score_

-766.0530530297632

In [187]:
# parameter tuning grid searchCV
from sklearn.model_selection import GridSearchCV

In [188]:
regressor_grid = GridSearchCV(estimator =regressor1, param_grid=param_grid_regressor,
                              cv = 5, verbose =2,
                              n_jobs= -1,  scoring = "neg_mean_squared_error")

In [189]:
regressor_grid.fit(X_model, y_model)

Fitting 5 folds for each of 3072 candidates, totalling 15360 fits


GridSearchCV(cv=5, estimator=SVR(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10, 100, 150, 200],
                         'degree': [1, 2, 3, 4, 5, 6, 7, 8],
                         'epsilon': [0.1, 1, 2, 4, 6, 10, 15, 20],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             scoring='neg_mean_squared_error', verbose=2)

In [190]:
regressor_grid.best_params_

{'C': 200, 'degree': 1, 'epsilon': 6, 'gamma': 'scale', 'kernel': 'rbf'}

In [191]:
regressor_grid.best_score_

-764.5175034425422

In [168]:
 # manual search engine
regressor2 = svm.SVR(kernel='rbf',
    degree=1,
    gamma='scale',
    coef0=0.0,
    tol=0.001,
    C=200,
    epsilon=6,)

In [169]:
regressor2.fit(X_train, y_train)

SVR(C=200, degree=1, epsilon=6)

In [170]:
y_pred2 = regressor2.predict(X_test)

In [171]:
y_pred_train2 = regressor2.predict(X_train)

In [172]:
y_pred_val2 = regressor2.predict(X_val)

In [173]:
y_pred_extest2 = regressor2.predict(X_extest)

In [174]:
y_pred_model2 = regressor2.predict(X_model)

In [175]:
  # model evaluation for testing set
  mae1 = metrics.mean_absolute_error(y_test, y_pred2)
  mse1 = metrics.mean_squared_error(y_test, y_pred2)
  r21 = metrics.r2_score(y_test, y_pred2)

In [176]:
print("The model performance for testing set")
print("--------------------------------------")
print('MAE is {}'.format(mae1))
print('MSE is {}'.format(mse1))
print('R2 score is {}'.format(r21))

The model performance for testing set
--------------------------------------
MAE is 15.004355864682648
MSE is 503.48149324274095
R2 score is 0.6546655518535002


In [177]:
 # model evaluation for training set
mae11 = metrics.mean_absolute_error(y_train, y_pred_train2)
mse11 = metrics.mean_squared_error(y_train, y_pred_train2)
r211 = metrics.r2_score(y_train, y_pred_train2)

In [178]:
print("The model performance for training set")
print("--------------------------------------")
print('MAE is {}'.format(mae11))
print('MSE is {}'.format(mse11))
print('R2 score is {}'.format(r211))

The model performance for training set
--------------------------------------
MAE is 13.590916460389275
MSE is 588.5015261084696
R2 score is 0.7762742985949151


In [179]:
  # model evaluation for ex-testing set
  maeext1 = metrics.mean_absolute_error(y_extest, y_pred_extest2)
  mseext1 = metrics.mean_squared_error(y_extest, y_pred_extest2)
  r2ext1 = metrics.r2_score(y_extest, y_pred_extest2)

In [180]:
print("The model performance for Ex-testing set")
print("--------------------------------------")
print('MAE is {}'.format(maeext1))
print('MSE is {}'.format(mseext1))
print('R2 score is {}'.format(r2ext1))

The model performance for Ex-testing set
--------------------------------------
MAE is 17.044821686890504
MSE is 632.8931537846219
R2 score is 0.7783378570487696


In [181]:
# model evaluation for val set
maeval1 = metrics.mean_absolute_error(y_val, y_pred_val2)
mseval1 = metrics.mean_squared_error(y_val, y_pred_val2)
r2val1 = metrics.r2_score(y_val, y_pred_val2)

In [182]:
print("The model performance for val set")
print("--------------------------------------")
print('MAE is {}'.format(maeval1))
print('MSE is {}'.format(mseval1))
print('R2 score is {}'.format(r2val1))

The model performance for val set
--------------------------------------
MAE is 17.33913244419098
MSE is 589.7953401123901
R2 score is 0.8251170483151444


In [183]:
 # model evaluation for modeling set
maemod1 = metrics.mean_absolute_error(y_model, y_pred_model2)
msemod1 = metrics.mean_squared_error(y_model, y_pred_model2)
r2mod1 = metrics.r2_score(y_model, y_pred_model2)

In [184]:
print("The model performance for modeling set")
print("--------------------------------------")
print('MAE is {}'.format(maemod1))
print('MSE is {}'.format(msemod1))
print('R2 score is {}'.format(r2mod1))

The model performance for modeling set
--------------------------------------
MAE is 13.864284805360837
MSE is 569.4265939239176
R2 score is 0.7803590368375928


In [185]:
cvscoretra1 = (-cross_val_score(regressor2,X_model,y_model.ravel(),cv=5).mean())

In [186]:
print("The CV score for modeling dataset")
print("--------------------------------------")
print (-cross_val_score(regressor2,X_model,y_model.ravel(),cv=5))
print('Q2 is {}'.format(cvscoretra1))


The CV score for Whoke dataset
--------------------------------------
[-0.84623858 -0.5466597  -0.56297077 -0.52770482 -0.79684353]
Q2 is -0.6560834809833694
